/**
* Generated by LEA for Arma 3
* Version: 2.0.22
* Wed Aug 27 01:20:14 CEST 2014
* Mission file name: free%20Ukraine.Chernarus
* Mission name: free%20Ukraine.Chernarus
* Required mods:
* + ArmA 3
* + AGM
* + Russians
* 
* Call the script: _dummy = [] execvm "lea\loadoutMultiplayer.sqf";
* 
*/

/**
* Loadout for crates
*/


/**
* Loadout for soldiers
*/

//No named soldiers in this mission.
