/**
* Generated by LEA for Arma 3
* Version: 2.0.22
* Tue Sep 09 19:33:21 CEST 2014
* Mission file name: freeUkrainev5.Chernarus
* Mission name: freeUkrainev5.Chernarus
* Required mods:
* + Russians
* + ArmA 3
* + ACRE
* + AGM
* 
* Call the script: _dummy = [] execvm "lea\loadoutServer.sqf";
* 
*/

/**
* Loadout for crates
*/

  clearweaponcargoGlobal Handys;
  clearmagazinecargoGlobal Handys;
  clearitemcargoGlobal Handys;

  Handys addmagazinecargoGlobal ["Titan_AA",4];
  Handys addmagazinecargoGlobal ["DemoCharge_Remote_Mag",5];
  Handys additemcargoGlobal ["ACRE_PRC343",15];
  Handys additemcargoGlobal ["ACRE_PRC117F",5];
  Handys additemcargoGlobal ["ACRE_PRC148_UHF",15];
  Handys additemcargoGlobal ["ACRE_PRC148",15];

  clearweaponcargoGlobal Wasserpistolen;
  clearmagazinecargoGlobal Wasserpistolen;
  clearitemcargoGlobal Wasserpistolen;

  Wasserpistolen addmagazinecargoGlobal ["150Rnd_762x51_Box_Tracer",15];
  Wasserpistolen addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",60];
  Wasserpistolen addmagazinecargoGlobal ["150Rnd_762x51_Box",10];
  Wasserpistolen additemcargoGlobal ["optic_Hamr",14];
  Wasserpistolen additemcargoGlobal ["optic_Arco",14];
  Wasserpistolen additemcargoGlobal ["optic_MRCO",14];
  Wasserpistolen additemcargoGlobal ["optic_sud_aim",14];
  Wasserpistolen additemcargoGlobal ["muzzle_snds_H",5];

  clearweaponcargoGlobal zusatz;
  clearmagazinecargoGlobal zusatz;
  clearitemcargoGlobal zusatz;

  zusatz additemcargoGlobal ["AGM_Bandage",120];
  zusatz additemcargoGlobal ["AGM_Epipen",40];
  zusatz additemcargoGlobal ["AGM_Bloodbag",20];
  zusatz additemcargoGlobal ["AGM_EarBuds",10];
  zusatz additemcargoGlobal ["AGM_Morphine",40];

  clearweaponcargoGlobal Wasserpistolen_1;
  clearmagazinecargoGlobal Wasserpistolen_1;
  clearitemcargoGlobal Wasserpistolen_1;

  Wasserpistolen_1 addweaponcargoGlobal ["arifle_SUD_M4A1_grip",14];
  Wasserpistolen_1 addweaponcargoGlobal ["LMG_Zafir_F",5];
  Wasserpistolen_1 addweaponcargoGlobal ["arifle_SUD_M4A1_GL",2];
  Wasserpistolen_1 addweaponcargoGlobal ["launch_B_Titan_F",2];
  Wasserpistolen_1 addmagazinecargoGlobal ["Titan_AA",5];

  clearweaponcargoGlobal ae_ru;
  clearmagazinecargoGlobal ae_ru;
  clearitemcargoGlobal ae_ru;

  ae_ru addmagazinecargoGlobal ["Titan_AA",4];
  ae_ru addmagazinecargoGlobal ["DemoCharge_Remote_Mag",5];
  ae_ru additemcargoGlobal ["AGM_Bandage",10];
  ae_ru additemcargoGlobal ["AGM_Epipen",10];
  ae_ru additemcargoGlobal ["AGM_Bloodbag",1];
  ae_ru additemcargoGlobal ["AGM_Morphine",10];

  clearweaponcargoGlobal ae_ru_1;
  clearmagazinecargoGlobal ae_ru_1;
  clearitemcargoGlobal ae_ru_1;

  ae_ru_1 addmagazinecargoGlobal ["Titan_AA",3];
  ae_ru_1 addmagazinecargoGlobal ["DemoCharge_Remote_Mag",5];
  ae_ru_1 additemcargoGlobal ["AGM_Bandage",21];
  ae_ru_1 additemcargoGlobal ["AGM_Epipen",11];
  ae_ru_1 additemcargoGlobal ["AGM_Bloodbag",2];
  ae_ru_1 additemcargoGlobal ["AGM_Morphine",11];

  clearweaponcargoGlobal ae_ru_2;
  clearmagazinecargoGlobal ae_ru_2;
  clearitemcargoGlobal ae_ru_2;

  ae_ru_2 addmagazinecargoGlobal ["Titan_AA",3];
  ae_ru_2 addmagazinecargoGlobal ["DemoCharge_Remote_Mag",5];
  ae_ru_2 additemcargoGlobal ["AGM_Bandage",60];
  ae_ru_2 additemcargoGlobal ["AGM_Epipen",20];
  ae_ru_2 additemcargoGlobal ["AGM_Bloodbag",5];
  ae_ru_2 additemcargoGlobal ["AGM_Morphine",20];


/**
* Loadout for soldiers units
*/

if (!isNil "s_squadl") then {
removeallweapons s_squadl;
removeallassigneditems s_squadl;
removeBackpack s_squadl;
removeVest s_squadl;
removeHeadgear s_squadl;
removeUniform s_squadl;
removeGoggles s_squadl;

s_squadl addWeapon "ItemMap";
s_squadl addWeapon "ItemWatch";
s_squadl addWeapon "ItemCompass";
s_squadl addWeapon "ItemGPS";
s_squadl addWeapon "H_HelmetB_plain_mcamo";
s_squadl addWeapon "NVGoggles_INDEP";
s_squadl addWeapon "Rangefinder_RU";
s_squadl addBackpack "B_TacticalPack_blk";
(backpackContainer s_squadl) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",1];
s_squadl addWeapon "arifle_SUD_M4A1";
removeBackpack s_squadl;
s_squadl addPrimaryWeaponItem "optic_Hamr";
s_squadl addBackpack "B_Carryall_khk";
clearItemCargoGlobal (backpackContainer s_squadl);
clearMagazineCargoGlobal (backpackContainer s_squadl);
clearWeaponCargoGlobal (backpackContainer s_squadl);
(backpackContainer s_squadl) additemcargoGlobal ["AGM_Bandage",20];
(backpackContainer s_squadl) additemcargoGlobal ["AGM_Epipen",3];
(backpackContainer s_squadl) additemcargoGlobal ["AGM_Bloodbag",1];
(backpackContainer s_squadl) additemcargoGlobal ["AGM_Morphine",6];
(backpackContainer s_squadl) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",3];
s_squadl addItemToBackpack "SmokeShell";
s_squadl addItemToBackpack "SmokeShell";
s_squadl addItemToBackpack "SmokeShell";
s_squadl addItemToBackpack "SmokeShell";
s_squadl addItemToBackpack "SmokeShell";
s_squadl addItemToBackpack "SmokeShellRed";
s_squadl addItemToBackpack "SmokeShellRed";
s_squadl addItemToBackpack "SmokeShellRed";
s_squadl addVest "V_TacVest_khk";
clearItemCargoGlobal (vestContainer s_squadl);
clearMagazineCargoGlobal (vestContainer s_squadl);
clearWeaponCargoGlobal (vestContainer s_squadl);
(vestContainer s_squadl) additemcargoGlobal ["ACRE_PRC343",1];
(vestContainer s_squadl) additemcargoGlobal ["AGM_EarBuds",1];
(vestContainer s_squadl) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",6];
s_squadl forceAddUniform "U_B_SpecopsUniform_sgg";
clearItemCargoGlobal (uniformContainer s_squadl);
clearMagazineCargoGlobal (uniformContainer s_squadl);
clearWeaponCargoGlobal (uniformContainer s_squadl);
(uniformContainer s_squadl) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",5];
s_squadl addWeapon "ACRE_PRC148_UHF";
s_squadl selectWeapon (primaryWeapon s_squadl);
};

if (!isNil "s_ftl_a") then {
removeallweapons s_ftl_a;
removeallassigneditems s_ftl_a;
removeBackpack s_ftl_a;
removeVest s_ftl_a;
removeHeadgear s_ftl_a;
removeUniform s_ftl_a;
removeGoggles s_ftl_a;

s_ftl_a addWeapon "ItemMap";
s_ftl_a addWeapon "ItemWatch";
s_ftl_a addWeapon "ItemCompass";
s_ftl_a addWeapon "ItemGPS";
s_ftl_a addWeapon "H_HelmetB_plain_mcamo";
s_ftl_a addWeapon "NVGoggles_INDEP";
s_ftl_a addWeapon "Rangefinder_RU";
s_ftl_a addBackpack "B_TacticalPack_blk";
(backpackContainer s_ftl_a) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",1];
s_ftl_a addWeapon "arifle_SUD_M4A1";
removeBackpack s_ftl_a;
s_ftl_a addPrimaryWeaponItem "optic_Hamr";
s_ftl_a addBackpack "B_Carryall_khk";
clearItemCargoGlobal (backpackContainer s_ftl_a);
clearMagazineCargoGlobal (backpackContainer s_ftl_a);
clearWeaponCargoGlobal (backpackContainer s_ftl_a);
(backpackContainer s_ftl_a) additemcargoGlobal ["AGM_Bandage",20];
(backpackContainer s_ftl_a) additemcargoGlobal ["AGM_Epipen",3];
(backpackContainer s_ftl_a) additemcargoGlobal ["AGM_Bloodbag",1];
(backpackContainer s_ftl_a) additemcargoGlobal ["AGM_Morphine",6];
(backpackContainer s_ftl_a) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",10];
s_ftl_a addItemToBackpack "SmokeShellGreen";
s_ftl_a addItemToBackpack "SmokeShellGreen";
s_ftl_a addItemToBackpack "SmokeShellGreen";
s_ftl_a addItemToBackpack "SmokeShell";
s_ftl_a addItemToBackpack "SmokeShell";
s_ftl_a addItemToBackpack "SmokeShell";
s_ftl_a addItemToBackpack "SmokeShellRed";
s_ftl_a addItemToBackpack "SmokeShellRed";
s_ftl_a addVest "V_TacVest_khk";
clearItemCargoGlobal (vestContainer s_ftl_a);
clearMagazineCargoGlobal (vestContainer s_ftl_a);
clearWeaponCargoGlobal (vestContainer s_ftl_a);
(vestContainer s_ftl_a) additemcargoGlobal ["ACRE_PRC343",1];
(vestContainer s_ftl_a) additemcargoGlobal ["AGM_EarBuds",1];
(vestContainer s_ftl_a) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",10];
s_ftl_a forceAddUniform "U_B_SpecopsUniform_sgg";
clearItemCargoGlobal (uniformContainer s_ftl_a);
clearMagazineCargoGlobal (uniformContainer s_ftl_a);
clearWeaponCargoGlobal (uniformContainer s_ftl_a);
(uniformContainer s_ftl_a) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",5];
s_ftl_a addWeapon "ACRE_PRC148";
s_ftl_a selectWeapon (primaryWeapon s_ftl_a);
};

if (!isNil "s_alpha_aa") then {
removeallweapons s_alpha_aa;
removeallassigneditems s_alpha_aa;
removeBackpack s_alpha_aa;
removeVest s_alpha_aa;
removeHeadgear s_alpha_aa;
removeUniform s_alpha_aa;
removeGoggles s_alpha_aa;

s_alpha_aa addWeapon "ItemMap";
s_alpha_aa addWeapon "ItemWatch";
s_alpha_aa addWeapon "ItemCompass";
s_alpha_aa addWeapon "ItemGPS";
s_alpha_aa addWeapon "H_HelmetB_plain_mcamo";
s_alpha_aa addWeapon "NVGoggles_INDEP";
s_alpha_aa addWeapon "Binocular";
s_alpha_aa addBackpack "B_TacticalPack_blk";
(backpackContainer s_alpha_aa) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",1];
s_alpha_aa addWeapon "arifle_SUD_M4A1";
removeBackpack s_alpha_aa;
s_alpha_aa addPrimaryWeaponItem "optic_Hamr";
s_alpha_aa addBackpack "B_TacticalPack_blk";
(backpackContainer s_alpha_aa) addmagazinecargoGlobal ["Titan_AA",1];
s_alpha_aa addWeapon "launch_B_Titan_F";
removeBackpack s_alpha_aa;
s_alpha_aa addBackpack "B_Carryall_khk";
clearItemCargoGlobal (backpackContainer s_alpha_aa);
clearMagazineCargoGlobal (backpackContainer s_alpha_aa);
clearWeaponCargoGlobal (backpackContainer s_alpha_aa);
(backpackContainer s_alpha_aa) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",7];
(backpackContainer s_alpha_aa) addmagazinecargoGlobal ["Titan_AA",2];
s_alpha_aa addVest "V_TacVest_khk";
clearItemCargoGlobal (vestContainer s_alpha_aa);
clearMagazineCargoGlobal (vestContainer s_alpha_aa);
clearWeaponCargoGlobal (vestContainer s_alpha_aa);
(vestContainer s_alpha_aa) additemcargoGlobal ["AGM_Bandage",20];
(vestContainer s_alpha_aa) additemcargoGlobal ["AGM_Epipen",3];
(vestContainer s_alpha_aa) additemcargoGlobal ["AGM_Bloodbag",1];
(vestContainer s_alpha_aa) additemcargoGlobal ["AGM_EarBuds",1];
(vestContainer s_alpha_aa) additemcargoGlobal ["AGM_Morphine",6];
s_alpha_aa forceAddUniform "U_B_SpecopsUniform_sgg";
clearItemCargoGlobal (uniformContainer s_alpha_aa);
clearMagazineCargoGlobal (uniformContainer s_alpha_aa);
clearWeaponCargoGlobal (uniformContainer s_alpha_aa);
(uniformContainer s_alpha_aa) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",5];
s_alpha_aa addWeapon "ACRE_PRC343";
s_alpha_aa selectWeapon (primaryWeapon s_alpha_aa);
};

if (!isNil "s_alpha_aat") then {
removeallweapons s_alpha_aat;
removeallassigneditems s_alpha_aat;
removeBackpack s_alpha_aat;
removeVest s_alpha_aat;
removeHeadgear s_alpha_aat;
removeUniform s_alpha_aat;
removeGoggles s_alpha_aat;

s_alpha_aat addWeapon "ItemMap";
s_alpha_aat addWeapon "ItemWatch";
s_alpha_aat addWeapon "ItemCompass";
s_alpha_aat addWeapon "ItemGPS";
s_alpha_aat addWeapon "H_HelmetB_plain_mcamo";
s_alpha_aat addWeapon "NVGoggles_INDEP";
s_alpha_aat addWeapon "Rangefinder_RU";
s_alpha_aat addBackpack "B_TacticalPack_blk";
(backpackContainer s_alpha_aat) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",1];
s_alpha_aat addWeapon "arifle_SUD_M4A1";
removeBackpack s_alpha_aat;
s_alpha_aat addPrimaryWeaponItem "optic_Hamr";
s_alpha_aat addBackpack "B_Carryall_khk";
clearItemCargoGlobal (backpackContainer s_alpha_aat);
clearMagazineCargoGlobal (backpackContainer s_alpha_aat);
clearWeaponCargoGlobal (backpackContainer s_alpha_aat);
(backpackContainer s_alpha_aat) additemcargoGlobal ["AGM_Bandage",20];
(backpackContainer s_alpha_aat) additemcargoGlobal ["AGM_Epipen",3];
(backpackContainer s_alpha_aat) additemcargoGlobal ["AGM_Bloodbag",1];
(backpackContainer s_alpha_aat) additemcargoGlobal ["AGM_Morphine",6];
(backpackContainer s_alpha_aat) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",5];
(backpackContainer s_alpha_aat) addmagazinecargoGlobal ["Titan_AA",1];
s_alpha_aat addVest "V_TacVest_khk";
clearItemCargoGlobal (vestContainer s_alpha_aat);
clearMagazineCargoGlobal (vestContainer s_alpha_aat);
clearWeaponCargoGlobal (vestContainer s_alpha_aat);
(vestContainer s_alpha_aat) additemcargoGlobal ["AGM_EarBuds",1];
(vestContainer s_alpha_aat) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",5];
s_alpha_aat forceAddUniform "U_B_SpecopsUniform_sgg";
clearItemCargoGlobal (uniformContainer s_alpha_aat);
clearMagazineCargoGlobal (uniformContainer s_alpha_aat);
clearWeaponCargoGlobal (uniformContainer s_alpha_aat);
(uniformContainer s_alpha_aat) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",5];
s_alpha_aat addWeapon "ACRE_PRC343";
s_alpha_aat selectWeapon (primaryWeapon s_alpha_aat);
};

if (!isNil "s_alpha_medic") then {
removeallweapons s_alpha_medic;
removeallassigneditems s_alpha_medic;
removeBackpack s_alpha_medic;
removeVest s_alpha_medic;
removeHeadgear s_alpha_medic;
removeUniform s_alpha_medic;
removeGoggles s_alpha_medic;

s_alpha_medic addWeapon "ItemMap";
s_alpha_medic addWeapon "ItemWatch";
s_alpha_medic addWeapon "ItemCompass";
s_alpha_medic addWeapon "ItemGPS";
s_alpha_medic addWeapon "H_HelmetB_plain_mcamo";
s_alpha_medic addWeapon "NVGoggles_INDEP";
s_alpha_medic addWeapon "Binocular";
s_alpha_medic addBackpack "B_TacticalPack_blk";
(backpackContainer s_alpha_medic) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",1];
s_alpha_medic addWeapon "arifle_SUD_M4A1";
removeBackpack s_alpha_medic;
s_alpha_medic addPrimaryWeaponItem "optic_Hamr";
s_alpha_medic addBackpack "B_Carryall_khk";
clearItemCargoGlobal (backpackContainer s_alpha_medic);
clearMagazineCargoGlobal (backpackContainer s_alpha_medic);
clearWeaponCargoGlobal (backpackContainer s_alpha_medic);
(backpackContainer s_alpha_medic) additemcargoGlobal ["AGM_Bandage",70];
(backpackContainer s_alpha_medic) additemcargoGlobal ["AGM_Epipen",20];
(backpackContainer s_alpha_medic) additemcargoGlobal ["AGM_Bloodbag",8];
(backpackContainer s_alpha_medic) additemcargoGlobal ["AGM_Morphine",30];
s_alpha_medic addItemToBackpack "SmokeShell";
s_alpha_medic addItemToBackpack "SmokeShell";
s_alpha_medic addVest "V_TacVest_khk";
clearItemCargoGlobal (vestContainer s_alpha_medic);
clearMagazineCargoGlobal (vestContainer s_alpha_medic);
clearWeaponCargoGlobal (vestContainer s_alpha_medic);
(vestContainer s_alpha_medic) additemcargoGlobal ["AGM_EarBuds",1];
(vestContainer s_alpha_medic) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",10];
s_alpha_medic addItemToVest "SmokeShellRed";
s_alpha_medic forceAddUniform "U_B_SpecopsUniform_sgg";
clearItemCargoGlobal (uniformContainer s_alpha_medic);
clearMagazineCargoGlobal (uniformContainer s_alpha_medic);
clearWeaponCargoGlobal (uniformContainer s_alpha_medic);
(uniformContainer s_alpha_medic) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",5];
s_alpha_medic addWeapon "ACRE_PRC343";
s_alpha_medic selectWeapon (primaryWeapon s_alpha_medic);
};

if (!isNil "s_FTL_bravo") then {
removeallweapons s_FTL_bravo;
removeallassigneditems s_FTL_bravo;
removeBackpack s_FTL_bravo;
removeVest s_FTL_bravo;
removeHeadgear s_FTL_bravo;
removeUniform s_FTL_bravo;
removeGoggles s_FTL_bravo;

s_FTL_bravo addWeapon "ItemMap";
s_FTL_bravo addWeapon "ItemWatch";
s_FTL_bravo addWeapon "ItemCompass";
s_FTL_bravo addWeapon "ItemGPS";
s_FTL_bravo addWeapon "H_HelmetB_plain_mcamo";
s_FTL_bravo addWeapon "NVGoggles_INDEP";
s_FTL_bravo addWeapon "Rangefinder_RU";
s_FTL_bravo addBackpack "B_TacticalPack_blk";
(backpackContainer s_FTL_bravo) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",1];
s_FTL_bravo addWeapon "arifle_SUD_M4A1";
removeBackpack s_FTL_bravo;
s_FTL_bravo addPrimaryWeaponItem "optic_Hamr";
s_FTL_bravo addBackpack "B_Carryall_khk";
clearItemCargoGlobal (backpackContainer s_FTL_bravo);
clearMagazineCargoGlobal (backpackContainer s_FTL_bravo);
clearWeaponCargoGlobal (backpackContainer s_FTL_bravo);
(backpackContainer s_FTL_bravo) additemcargoGlobal ["AGM_Bandage",20];
(backpackContainer s_FTL_bravo) additemcargoGlobal ["AGM_Epipen",3];
(backpackContainer s_FTL_bravo) additemcargoGlobal ["AGM_Bloodbag",1];
(backpackContainer s_FTL_bravo) additemcargoGlobal ["AGM_Morphine",6];
(backpackContainer s_FTL_bravo) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",15];
s_FTL_bravo addVest "V_TacVest_khk";
clearItemCargoGlobal (vestContainer s_FTL_bravo);
clearMagazineCargoGlobal (vestContainer s_FTL_bravo);
clearWeaponCargoGlobal (vestContainer s_FTL_bravo);
(vestContainer s_FTL_bravo) additemcargoGlobal ["ACRE_PRC343",1];
(vestContainer s_FTL_bravo) additemcargoGlobal ["AGM_EarBuds",1];
(vestContainer s_FTL_bravo) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",5];
s_FTL_bravo addItemToVest "SmokeShellGreen";
s_FTL_bravo addItemToVest "SmokeShellGreen";
s_FTL_bravo addItemToVest "SmokeShell";
s_FTL_bravo addItemToVest "SmokeShell";
s_FTL_bravo addItemToVest "SmokeShellRed";
s_FTL_bravo addItemToVest "SmokeShellRed";
s_FTL_bravo forceAddUniform "U_B_SpecopsUniform_sgg";
clearItemCargoGlobal (uniformContainer s_FTL_bravo);
clearMagazineCargoGlobal (uniformContainer s_FTL_bravo);
clearWeaponCargoGlobal (uniformContainer s_FTL_bravo);
(uniformContainer s_FTL_bravo) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",5];
s_FTL_bravo addWeapon "ACRE_PRC148";
s_FTL_bravo selectWeapon (primaryWeapon s_FTL_bravo);
};

if (!isNil "s_ar_bravo") then {
removeallweapons s_ar_bravo;
removeallassigneditems s_ar_bravo;
removeBackpack s_ar_bravo;
removeVest s_ar_bravo;
removeHeadgear s_ar_bravo;
removeUniform s_ar_bravo;
removeGoggles s_ar_bravo;

s_ar_bravo addWeapon "ItemMap";
s_ar_bravo addWeapon "ItemWatch";
s_ar_bravo addWeapon "ItemCompass";
s_ar_bravo addWeapon "ItemGPS";
s_ar_bravo addWeapon "H_Bandanna_camo";
s_ar_bravo addWeapon "NVGoggles_INDEP";
s_ar_bravo addWeapon "Binocular";
s_ar_bravo addBackpack "B_TacticalPack_blk";
(backpackContainer s_ar_bravo) addmagazinecargoGlobal ["150Rnd_762x51_Box_Tracer",1];
s_ar_bravo addWeapon "LMG_Zafir_F";
removeBackpack s_ar_bravo;
s_ar_bravo addPrimaryWeaponItem "optic_Hamr";
s_ar_bravo addBackpack "B_Carryall_khk";
clearItemCargoGlobal (backpackContainer s_ar_bravo);
clearMagazineCargoGlobal (backpackContainer s_ar_bravo);
clearWeaponCargoGlobal (backpackContainer s_ar_bravo);
(backpackContainer s_ar_bravo) additemcargoGlobal ["AGM_Bandage",20];
(backpackContainer s_ar_bravo) additemcargoGlobal ["AGM_SpareBarrel",1];
(backpackContainer s_ar_bravo) additemcargoGlobal ["AGM_Epipen",3];
(backpackContainer s_ar_bravo) additemcargoGlobal ["AGM_Bloodbag",1];
(backpackContainer s_ar_bravo) additemcargoGlobal ["AGM_Morphine",6];
(backpackContainer s_ar_bravo) addmagazinecargoGlobal ["150Rnd_762x51_Box_Tracer",4];
s_ar_bravo addItemToBackpack "SmokeShellGreen";
s_ar_bravo addItemToBackpack "SmokeShellGreen";
s_ar_bravo addVest "V_TacVest_khk";
clearItemCargoGlobal (vestContainer s_ar_bravo);
clearMagazineCargoGlobal (vestContainer s_ar_bravo);
clearWeaponCargoGlobal (vestContainer s_ar_bravo);
(vestContainer s_ar_bravo) additemcargoGlobal ["AGM_EarBuds",1];
(vestContainer s_ar_bravo) addmagazinecargoGlobal ["150Rnd_762x51_Box_Tracer",2];
s_ar_bravo addItemToVest "SmokeShell";
s_ar_bravo forceAddUniform "U_B_SpecopsUniform_sgg";
clearItemCargoGlobal (uniformContainer s_ar_bravo);
clearMagazineCargoGlobal (uniformContainer s_ar_bravo);
clearWeaponCargoGlobal (uniformContainer s_ar_bravo);
(uniformContainer s_ar_bravo) addmagazinecargoGlobal ["150Rnd_762x51_Box_Tracer",1];
s_ar_bravo addWeapon "ACRE_PRC343";
s_ar_bravo selectWeapon (primaryWeapon s_ar_bravo);
};

if (!isNil "s_ara_bravo") then {
removeallweapons s_ara_bravo;
removeallassigneditems s_ara_bravo;
removeBackpack s_ara_bravo;
removeVest s_ara_bravo;
removeHeadgear s_ara_bravo;
removeUniform s_ara_bravo;
removeGoggles s_ara_bravo;

s_ara_bravo addWeapon "ItemMap";
s_ara_bravo addWeapon "ItemWatch";
s_ara_bravo addWeapon "ItemCompass";
s_ara_bravo addWeapon "ItemGPS";
s_ara_bravo addWeapon "H_HelmetB_plain_mcamo";
s_ara_bravo addWeapon "NVGoggles_INDEP";
s_ara_bravo addWeapon "Binocular";
s_ara_bravo addBackpack "B_TacticalPack_blk";
(backpackContainer s_ara_bravo) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",1];
s_ara_bravo addWeapon "arifle_SUD_M4A1";
removeBackpack s_ara_bravo;
s_ara_bravo addPrimaryWeaponItem "optic_Hamr";
s_ara_bravo addBackpack "B_Carryall_khk";
clearItemCargoGlobal (backpackContainer s_ara_bravo);
clearMagazineCargoGlobal (backpackContainer s_ara_bravo);
clearWeaponCargoGlobal (backpackContainer s_ara_bravo);
(backpackContainer s_ara_bravo) additemcargoGlobal ["AGM_Bandage",20];
(backpackContainer s_ara_bravo) additemcargoGlobal ["AGM_Bloodbag",1];
(backpackContainer s_ara_bravo) addmagazinecargoGlobal ["150Rnd_762x51_Box_Tracer",4];
s_ara_bravo addItemToBackpack "SmokeShellGreen";
s_ara_bravo addItemToBackpack "SmokeShell";
s_ara_bravo addItemToBackpack "SmokeShellRed";
s_ara_bravo addVest "V_TacVest_khk";
clearItemCargoGlobal (vestContainer s_ara_bravo);
clearMagazineCargoGlobal (vestContainer s_ara_bravo);
clearWeaponCargoGlobal (vestContainer s_ara_bravo);
(vestContainer s_ara_bravo) additemcargoGlobal ["AGM_Epipen",3];
(vestContainer s_ara_bravo) additemcargoGlobal ["AGM_EarBuds",1];
(vestContainer s_ara_bravo) additemcargoGlobal ["AGM_Morphine",6];
(vestContainer s_ara_bravo) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",10];
s_ara_bravo forceAddUniform "U_B_SpecopsUniform_sgg";
clearItemCargoGlobal (uniformContainer s_ara_bravo);
clearMagazineCargoGlobal (uniformContainer s_ara_bravo);
clearWeaponCargoGlobal (uniformContainer s_ara_bravo);
(uniformContainer s_ara_bravo) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",5];
s_ara_bravo addWeapon "ACRE_PRC343";
s_ara_bravo selectWeapon (primaryWeapon s_ara_bravo);
};

if (!isNil "s_grend_Barvo") then {
removeallweapons s_grend_Barvo;
removeallassigneditems s_grend_Barvo;
removeBackpack s_grend_Barvo;
removeVest s_grend_Barvo;
removeHeadgear s_grend_Barvo;
removeUniform s_grend_Barvo;
removeGoggles s_grend_Barvo;

s_grend_Barvo addWeapon "ItemMap";
s_grend_Barvo addWeapon "ItemWatch";
s_grend_Barvo addWeapon "ItemCompass";
s_grend_Barvo addWeapon "ItemGPS";
s_grend_Barvo addWeapon "H_HelmetB_plain_mcamo";
s_grend_Barvo addWeapon "NVGoggles_INDEP";
s_grend_Barvo addWeapon "Binocular";
s_grend_Barvo addBackpack "B_TacticalPack_blk";
(backpackContainer s_grend_Barvo) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",1];
s_grend_Barvo addWeapon "arifle_SUD_M4A1_GL";
removeBackpack s_grend_Barvo;
s_grend_Barvo addPrimaryWeaponItem "optic_Hamr";
s_grend_Barvo addBackpack "B_Carryall_khk";
clearItemCargoGlobal (backpackContainer s_grend_Barvo);
clearMagazineCargoGlobal (backpackContainer s_grend_Barvo);
clearWeaponCargoGlobal (backpackContainer s_grend_Barvo);
(backpackContainer s_grend_Barvo) additemcargoGlobal ["AGM_Morphine",7];
(backpackContainer s_grend_Barvo) addmagazinecargoGlobal ["SUD_1Rnd_HE_M203",15];
(backpackContainer s_grend_Barvo) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",12];
s_grend_Barvo addItemToBackpack "DemoCharge_Remote_Mag";
s_grend_Barvo addItemToBackpack "DemoCharge_Remote_Mag";
s_grend_Barvo addItemToBackpack "DemoCharge_Remote_Mag";
s_grend_Barvo addItemToBackpack "DemoCharge_Remote_Mag";
s_grend_Barvo addVest "V_TacVest_khk";
clearItemCargoGlobal (vestContainer s_grend_Barvo);
clearMagazineCargoGlobal (vestContainer s_grend_Barvo);
clearWeaponCargoGlobal (vestContainer s_grend_Barvo);
(vestContainer s_grend_Barvo) additemcargoGlobal ["AGM_Bandage",20];
(vestContainer s_grend_Barvo) additemcargoGlobal ["AGM_Epipen",6];
(vestContainer s_grend_Barvo) additemcargoGlobal ["AGM_Bloodbag",1];
(vestContainer s_grend_Barvo) additemcargoGlobal ["AGM_EarBuds",1];
(vestContainer s_grend_Barvo) addmagazinecargoGlobal ["SUD_1Rnd_HE_M203",30];
s_grend_Barvo forceAddUniform "U_B_SpecopsUniform_sgg";
clearItemCargoGlobal (uniformContainer s_grend_Barvo);
clearMagazineCargoGlobal (uniformContainer s_grend_Barvo);
clearWeaponCargoGlobal (uniformContainer s_grend_Barvo);
(uniformContainer s_grend_Barvo) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",5];
s_grend_Barvo addWeapon "ACRE_PRC343";
s_grend_Barvo selectWeapon (primaryWeapon s_grend_Barvo);
};

if (!isNil "s_ftl_charlie") then {
removeallweapons s_ftl_charlie;
removeallassigneditems s_ftl_charlie;
removeBackpack s_ftl_charlie;
removeVest s_ftl_charlie;
removeHeadgear s_ftl_charlie;
removeUniform s_ftl_charlie;
removeGoggles s_ftl_charlie;

s_ftl_charlie addWeapon "ItemMap";
s_ftl_charlie addWeapon "ItemWatch";
s_ftl_charlie addWeapon "ItemCompass";
s_ftl_charlie addWeapon "ItemGPS";
s_ftl_charlie addWeapon "H_HelmetB_plain_mcamo";
s_ftl_charlie addWeapon "NVGoggles_INDEP";
s_ftl_charlie addWeapon "Rangefinder_RU";
s_ftl_charlie addBackpack "B_TacticalPack_blk";
(backpackContainer s_ftl_charlie) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",1];
s_ftl_charlie addWeapon "arifle_SUD_M4A1";
removeBackpack s_ftl_charlie;
s_ftl_charlie addPrimaryWeaponItem "optic_Hamr";
s_ftl_charlie addBackpack "B_Carryall_khk";
clearItemCargoGlobal (backpackContainer s_ftl_charlie);
clearMagazineCargoGlobal (backpackContainer s_ftl_charlie);
clearWeaponCargoGlobal (backpackContainer s_ftl_charlie);
(backpackContainer s_ftl_charlie) additemcargoGlobal ["AGM_Bandage",20];
(backpackContainer s_ftl_charlie) additemcargoGlobal ["AGM_Epipen",4];
(backpackContainer s_ftl_charlie) additemcargoGlobal ["AGM_Bloodbag",1];
(backpackContainer s_ftl_charlie) additemcargoGlobal ["AGM_Morphine",6];
(backpackContainer s_ftl_charlie) addmagazinecargoGlobal ["150Rnd_762x51_Box_Tracer",2];
(backpackContainer s_ftl_charlie) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",5];
s_ftl_charlie addItemToBackpack "SmokeShellGreen";
s_ftl_charlie addItemToBackpack "SmokeShellGreen";
s_ftl_charlie addItemToBackpack "SmokeShell";
s_ftl_charlie addItemToBackpack "SmokeShell";
s_ftl_charlie addItemToBackpack "SmokeShellRed";
s_ftl_charlie addItemToBackpack "SmokeShellRed";
s_ftl_charlie addItemToBackpack "SmokeShellRed";
s_ftl_charlie addVest "V_TacVest_khk";
clearItemCargoGlobal (vestContainer s_ftl_charlie);
clearMagazineCargoGlobal (vestContainer s_ftl_charlie);
clearWeaponCargoGlobal (vestContainer s_ftl_charlie);
(vestContainer s_ftl_charlie) additemcargoGlobal ["ACRE_PRC343",1];
(vestContainer s_ftl_charlie) additemcargoGlobal ["AGM_EarBuds",1];
(vestContainer s_ftl_charlie) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",10];
s_ftl_charlie forceAddUniform "U_B_SpecopsUniform_sgg";
clearItemCargoGlobal (uniformContainer s_ftl_charlie);
clearMagazineCargoGlobal (uniformContainer s_ftl_charlie);
clearWeaponCargoGlobal (uniformContainer s_ftl_charlie);
(uniformContainer s_ftl_charlie) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",5];
s_ftl_charlie addWeapon "ACRE_PRC148";
s_ftl_charlie selectWeapon (primaryWeapon s_ftl_charlie);
};

if (!isNil "s_ar_charlie") then {
removeallweapons s_ar_charlie;
removeallassigneditems s_ar_charlie;
removeBackpack s_ar_charlie;
removeVest s_ar_charlie;
removeHeadgear s_ar_charlie;
removeUniform s_ar_charlie;
removeGoggles s_ar_charlie;

s_ar_charlie addWeapon "ItemMap";
s_ar_charlie addWeapon "ItemWatch";
s_ar_charlie addWeapon "ItemCompass";
s_ar_charlie addWeapon "ItemGPS";
s_ar_charlie addWeapon "H_Bandanna_camo";
s_ar_charlie addWeapon "NVGoggles_INDEP";
s_ar_charlie addWeapon "Binocular";
s_ar_charlie addBackpack "B_TacticalPack_blk";
(backpackContainer s_ar_charlie) addmagazinecargoGlobal ["150Rnd_762x51_Box_Tracer",1];
s_ar_charlie addWeapon "LMG_Zafir_F";
removeBackpack s_ar_charlie;
s_ar_charlie addPrimaryWeaponItem "optic_Hamr";
s_ar_charlie addBackpack "B_Carryall_khk";
clearItemCargoGlobal (backpackContainer s_ar_charlie);
clearMagazineCargoGlobal (backpackContainer s_ar_charlie);
clearWeaponCargoGlobal (backpackContainer s_ar_charlie);
(backpackContainer s_ar_charlie) additemcargoGlobal ["AGM_Bandage",20];
(backpackContainer s_ar_charlie) additemcargoGlobal ["AGM_SpareBarrel",1];
(backpackContainer s_ar_charlie) additemcargoGlobal ["AGM_Epipen",3];
(backpackContainer s_ar_charlie) additemcargoGlobal ["AGM_Bloodbag",1];
(backpackContainer s_ar_charlie) additemcargoGlobal ["AGM_Morphine",6];
(backpackContainer s_ar_charlie) addmagazinecargoGlobal ["150Rnd_762x51_Box_Tracer",4];
s_ar_charlie addItemToBackpack "SmokeShell";
s_ar_charlie addVest "V_TacVest_khk";
clearItemCargoGlobal (vestContainer s_ar_charlie);
clearMagazineCargoGlobal (vestContainer s_ar_charlie);
clearWeaponCargoGlobal (vestContainer s_ar_charlie);
(vestContainer s_ar_charlie) additemcargoGlobal ["AGM_EarBuds",1];
(vestContainer s_ar_charlie) addmagazinecargoGlobal ["150Rnd_762x51_Box_Tracer",2];
s_ar_charlie addItemToVest "SmokeShell";
s_ar_charlie forceAddUniform "U_B_SpecopsUniform_sgg";
clearItemCargoGlobal (uniformContainer s_ar_charlie);
clearMagazineCargoGlobal (uniformContainer s_ar_charlie);
clearWeaponCargoGlobal (uniformContainer s_ar_charlie);
(uniformContainer s_ar_charlie) addmagazinecargoGlobal ["150Rnd_762x51_Box_Tracer",1];
s_ar_charlie addWeapon "ACRE_PRC343";
s_ar_charlie selectWeapon (primaryWeapon s_ar_charlie);
};

if (!isNil "s_ara_charlie") then {
removeallweapons s_ara_charlie;
removeallassigneditems s_ara_charlie;
removeBackpack s_ara_charlie;
removeVest s_ara_charlie;
removeHeadgear s_ara_charlie;
removeUniform s_ara_charlie;
removeGoggles s_ara_charlie;

s_ara_charlie addWeapon "ItemMap";
s_ara_charlie addWeapon "ItemWatch";
s_ara_charlie addWeapon "ItemCompass";
s_ara_charlie addWeapon "ItemGPS";
s_ara_charlie addWeapon "H_HelmetB_plain_mcamo";
s_ara_charlie addWeapon "NVGoggles_INDEP";
s_ara_charlie addWeapon "Binocular";
s_ara_charlie addBackpack "B_TacticalPack_blk";
(backpackContainer s_ara_charlie) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",1];
s_ara_charlie addWeapon "arifle_SUD_M4A1";
removeBackpack s_ara_charlie;
s_ara_charlie addPrimaryWeaponItem "optic_Hamr";
s_ara_charlie addBackpack "B_Carryall_khk";
clearItemCargoGlobal (backpackContainer s_ara_charlie);
clearMagazineCargoGlobal (backpackContainer s_ara_charlie);
clearWeaponCargoGlobal (backpackContainer s_ara_charlie);
(backpackContainer s_ara_charlie) addmagazinecargoGlobal ["150Rnd_762x51_Box_Tracer",4];
(backpackContainer s_ara_charlie) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",12];
s_ara_charlie addItemToBackpack "SmokeShell";
s_ara_charlie addItemToBackpack "SmokeShell";
s_ara_charlie addVest "V_TacVest_khk";
clearItemCargoGlobal (vestContainer s_ara_charlie);
clearMagazineCargoGlobal (vestContainer s_ara_charlie);
clearWeaponCargoGlobal (vestContainer s_ara_charlie);
(vestContainer s_ara_charlie) additemcargoGlobal ["AGM_Bandage",20];
(vestContainer s_ara_charlie) additemcargoGlobal ["AGM_Epipen",3];
(vestContainer s_ara_charlie) additemcargoGlobal ["AGM_Bloodbag",1];
(vestContainer s_ara_charlie) additemcargoGlobal ["AGM_EarBuds",1];
(vestContainer s_ara_charlie) additemcargoGlobal ["AGM_Morphine",6];
(vestContainer s_ara_charlie) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",4];
s_ara_charlie forceAddUniform "U_B_SpecopsUniform_sgg";
clearItemCargoGlobal (uniformContainer s_ara_charlie);
clearMagazineCargoGlobal (uniformContainer s_ara_charlie);
clearWeaponCargoGlobal (uniformContainer s_ara_charlie);
(uniformContainer s_ara_charlie) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",5];
s_ara_charlie addWeapon "ACRE_PRC343";
s_ara_charlie selectWeapon (primaryWeapon s_ara_charlie);
};

if (!isNil "s_medic_charlie") then {
removeallweapons s_medic_charlie;
removeallassigneditems s_medic_charlie;
removeBackpack s_medic_charlie;
removeVest s_medic_charlie;
removeHeadgear s_medic_charlie;
removeUniform s_medic_charlie;
removeGoggles s_medic_charlie;

s_medic_charlie addWeapon "ItemMap";
s_medic_charlie addWeapon "ItemWatch";
s_medic_charlie addWeapon "ItemCompass";
s_medic_charlie addWeapon "ItemGPS";
s_medic_charlie addWeapon "H_HelmetB_plain_mcamo";
s_medic_charlie addWeapon "NVGoggles_INDEP";
s_medic_charlie addWeapon "Binocular";
s_medic_charlie addBackpack "B_TacticalPack_blk";
(backpackContainer s_medic_charlie) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",1];
s_medic_charlie addWeapon "arifle_SUD_M4A1";
removeBackpack s_medic_charlie;
s_medic_charlie addPrimaryWeaponItem "optic_Hamr";
s_medic_charlie addBackpack "B_Carryall_khk";
clearItemCargoGlobal (backpackContainer s_medic_charlie);
clearMagazineCargoGlobal (backpackContainer s_medic_charlie);
clearWeaponCargoGlobal (backpackContainer s_medic_charlie);
(backpackContainer s_medic_charlie) additemcargoGlobal ["AGM_Bandage",60];
(backpackContainer s_medic_charlie) additemcargoGlobal ["AGM_Epipen",20];
(backpackContainer s_medic_charlie) additemcargoGlobal ["AGM_Bloodbag",10];
(backpackContainer s_medic_charlie) additemcargoGlobal ["AGM_Morphine",26];
(backpackContainer s_medic_charlie) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",10];
s_medic_charlie addVest "V_TacVest_khk";
clearItemCargoGlobal (vestContainer s_medic_charlie);
clearMagazineCargoGlobal (vestContainer s_medic_charlie);
clearWeaponCargoGlobal (vestContainer s_medic_charlie);
(vestContainer s_medic_charlie) additemcargoGlobal ["AGM_Bandage",40];
(vestContainer s_medic_charlie) additemcargoGlobal ["AGM_EarBuds",1];
(vestContainer s_medic_charlie) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",2];
s_medic_charlie forceAddUniform "U_B_SpecopsUniform_sgg";
clearItemCargoGlobal (uniformContainer s_medic_charlie);
clearMagazineCargoGlobal (uniformContainer s_medic_charlie);
clearWeaponCargoGlobal (uniformContainer s_medic_charlie);
(uniformContainer s_medic_charlie) addmagazinecargoGlobal ["SUD_30Rnd_556x45_Stanag",5];
s_medic_charlie addWeapon "ACRE_PRC343";
s_medic_charlie selectWeapon (primaryWeapon s_medic_charlie);
};

if (!isNil "Presse") then {
removeallweapons Presse;
removeallassigneditems Presse;
removeBackpack Presse;
removeVest Presse;
removeHeadgear Presse;
removeUniform Presse;
removeGoggles Presse;

Presse addWeapon "ItemMap";
Presse addWeapon "ItemWatch";
Presse addWeapon "ItemCompass";
Presse addWeapon "ItemGPS";
Presse addWeapon "H_Cap_press";
Presse addWeapon "NVGoggles_INDEP";
Presse addWeapon "Binocular";
Presse addBackpack "B_TacticalPack_blk";
(backpackContainer Presse) addmagazinecargoGlobal ["11Rnd_45ACP_Mag",1];
Presse addWeapon "hgun_Pistol_heavy_01_F";
removeBackpack Presse;
Presse addHandgunItem "optic_MRD";
Presse addBackpack "B_FieldPack_khk";
clearItemCargoGlobal (backpackContainer Presse);
clearMagazineCargoGlobal (backpackContainer Presse);
clearWeaponCargoGlobal (backpackContainer Presse);
Presse addVest "V_Press_F";
clearItemCargoGlobal (vestContainer Presse);
clearMagazineCargoGlobal (vestContainer Presse);
clearWeaponCargoGlobal (vestContainer Presse);
(vestContainer Presse) additemcargoGlobal ["ACRE_PRC343",1];
(vestContainer Presse) additemcargoGlobal ["AGM_EarBuds",1];
(vestContainer Presse) addmagazinecargoGlobal ["11Rnd_45ACP_Mag",5];
Presse forceAddUniform "U_I_G_Story_Protagonist_F";
clearItemCargoGlobal (uniformContainer Presse);
clearMagazineCargoGlobal (uniformContainer Presse);
clearWeaponCargoGlobal (uniformContainer Presse);
Presse addWeapon "ACRE_PRC148";
if (count weapons Presse > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons Presse) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     Presse selectWeapon (_muzzles select 0);
  }
  else {
     Presse selectWeapon _type;
  };
};
};

