leaFunction =  compile preprocessFileLineNumbers "lea\loadout-init.sqf"; call leaFunction;//line generated by LEA.
enableSaving[false,false];

setViewDistance 3000;

e12_tools_settings_admins = ["Coati","Rickyfox"];

// HC Client Code
if(isNil "paramsArray") then{ paramsArray=[0,0,0]};

//get mission parameter to see if 
//HeadlessClient is present and assign its name
if(paramsArray select 0 == 1) then{
	if(isServer) then{
		HCPresent = true;
		publicVariable "HCPresent";
	};
	if (!hasInterface && !isServer) then{
        waitUntil{!isNull player};
		HCName = name player; 
		publicVariable "HCName";
	};
} else{
	if(isServer) then{
		HCPresent = false;
		HCName = "NONE";
		publicVariable "HCPresent";
		publicVariable "HCName";
	};
};

waitUntil{!isNil "HCPresent"};
waitUntil{!isNil "HCName"};

fnc_spawnHCGroup=compile preprocessFileLineNumbers 'scripts\spawnGrp.sqf';
fnc_spawnHCAttack=compile preprocessFileLineNumbers 'scripts\spawnAttack.sqf';
fnc_spawnHCDefend=compile preprocessFileLineNumbers 'scripts\spawnDefend.sqf';

if(!isServer) then {waitUntil{!isNull player}};

 if (local player) then {
   player enableFatigue false;
   player addEventhandler ["Respawn", {player enableFatigue false}];
};

//[0, {destroy=[]execVM "scripts\destroyCity.sqf";}] call CBA_fnc_globalExecute;

    

